import { StyleSheet, Font } from "@react-pdf/renderer";

export const categoryColorsMap: Record<string, string> = {
  Entertainment: "#8B5CF6",
  Software: "#0EA5E9",
  Utilities: "#10B981",
  Productivity: "#F59E0B",
  "Cloud & Infrastructure": "#F43F5E",
  Finance: "#06B6D4",
  "Health & Fitness": "#D946EF",
  Education: "#84CC16",
  "News & Media": "#F97316",
  Other: "#14B8A6",
};

export const formatDate = (date: Date | string | null) => {
  if (!date) return "-";
  const d = new Date(date);
  return d.toLocaleDateString("de-DE", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

Font.register({
  family: "NotoSans",
  fonts: [
    {
      src: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf",
      fontWeight: "normal",
    },
    {
      src: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Bold.ttf",
      fontWeight: "bold",
    },
  ],
});

export const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: "#F8FAFC",
    fontFamily: "NotoSans",
    color: "#0F172A",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  coverContainer: {
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    padding: 20,
    borderRadius: 8,
    marginBottom: 10,
  },
  coverSubtitle: {
    fontSize: 7.5,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    letterSpacing: 2,
    color: "#0EA5E9",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  coverTitle: {
    fontSize: 18,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  coverMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#334155",
    paddingTop: 6,
    fontSize: 7.5,
    color: "#94A3B8",
  },
  sectionTitle: {
    fontSize: 8.5,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    color: "#4F46E5",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    paddingBottom: 2,
  },
  bodyText: { fontSize: 8, color: "#475569", lineHeight: 1.4 },
  boldText: { fontFamily: "NotoSans", fontWeight: "bold", color: "#0F172A" },
  kpiGrid: { flexDirection: "row", justifyContent: "space-between", gap: 6 },
  kpiCard: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 6,
    padding: 8,
    alignItems: "center",
  },
  kpiLabel: {
    fontSize: 6,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  kpiValue: {
    fontSize: 10,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    color: "#0F172A",
  },
  splitGrid: { flexDirection: "row", gap: 10 },
  splitCol: { flex: 1 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 4,
    fontSize: 7.5,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    alignItems: "center",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    paddingVertical: 5,
    paddingHorizontal: 8,
    alignItems: "center",
    fontSize: 7,
    backgroundColor: "#FFFFFF",
  },
  tableRowAlternate: { backgroundColor: "#F8FAFC" },
  categoryPill: { width: 3.5, height: 9, borderRadius: 1.5, marginRight: 6 },
  colName: { width: "30%", flexDirection: "row", alignItems: "center" },
  colCategory: { width: "20%" },
  colCycle: { width: "15%", textAlign: "center" },
  colPrice: {
    width: "15%",
    textAlign: "right",
    fontFamily: "NotoSans",
    fontWeight: "bold",
  },
  colStatus: { width: "20%", textAlign: "right" },
  colEventDate: { width: "15%" },
  colEventName: { width: "35%", flexDirection: "row", alignItems: "center" },
  colEventCategory: { width: "20%" },
  colEventSource: {
    width: "15%",
    textAlign: "center",
    textTransform: "capitalize",
  },
  colEventAmount: {
    width: "15%",
    textAlign: "right",
    fontFamily: "NotoSans",
    fontWeight: "bold",
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  progressTrack: {
    height: 4,
    backgroundColor: "#F1F5F9",
    borderRadius: 2,
    width: "100%",
    overflow: "hidden",
    marginTop: 1,
  },
  progressFill: { height: "100%", borderRadius: 2 },
  timelineItem: {
    flexDirection: "row",
    borderLeftWidth: 1,
    borderLeftColor: "#E2E8F0",
    paddingLeft: 10,
    marginLeft: 5,
    paddingBottom: 6,
    position: "relative",
  },
  timelineDot: {
    position: "absolute",
    left: -3,
    top: 2,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "#4F46E5",
  },
  timelineMeta: {
    fontSize: 6.5,
    fontFamily: "NotoSans",
    fontWeight: "bold",
    color: "#64748B",
    marginBottom: 1,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    textAlign: "center",
    fontSize: 6.5,
    color: "#94A3B8",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    paddingTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
  },
});
